services:
  grafana:
    image: grafana/grafana-oss:12.0.0
    restart: unless-stopped
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
    ports:
      - 127.0.0.1:3000:3000 # http://localhost:3000/
    volumes:
      - ./.configs/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./.configs/grafana/dashboards:/var/lib/grafana/dashboards:ro
      - ./.configs/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/main.yml:ro
      - ./.configs/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - grafana_storage:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v3.4.0
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./.configs/grafana/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_storage:/prometheus

  agent:
    image: grafana/agent:v0.44.2
    restart: unless-stopped
    cap_add:
      - SYS_TIME
    network_mode: host
    entrypoint:
      - /bin/grafana-agent
      - -config.file=/etc/agent/agent-config.yml
    volumes:
      - ./.configs/grafana/agent.yml:/etc/agent/agent-config.yml:ro
    depends_on:
      - prometheus

volumes:
  grafana_storage:
  prometheus_storage:
