services:
  dvr:
    image: offkai/srs-dvr
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - ./data:/data
    ports:
      - 127.0.0.1:3001:3001/tcp
      - 127.0.0.1:3002:3002/tcp
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://127.0.0.1:3001/ping || exit 1
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 20s
