services:
  srs:
    image: ossrs/srs:v6.0.166
    restart: unless-stopped
    environment:
      SRS_CONFIG_FILE: /opt/conf/origin.conf
      SRS_VHOST_HTTP_HOOKS_ON_DVR: http://localhost:3001/v1/s3
      SRS_EXPORTER_ENABLED: on
    env_file:
      - .env
    network_mode: host # Need to send webhooks to localhost
    # ports:
    #   - 127.0.0.1:1935:1935/tcp # RTMP
    #   - 127.0.0.1:1985:1985/tcp # API
    #   - 127.0.0.1:8080:8080/tcp # HTTP Live Streaming
    #   - 127.0.0.1:8000:8000/udp # WebRTC
    #   - 127.0.0.1:9972:9972/tcp # Prometheus metrics @ /metrics
    volumes:
      - ./.configs/srs/origin.conf:/opt/conf/origin.conf
      - ./data:/data

  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    restart: unless-stopped
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio:/data
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9001:9001 # http://localhost:9001
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  minio:
