services:
  dvr:
    image: offkai/srs-dvr
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - ./data:/data
    ports:
      - 127.0.0.1:3001:3001/tcp
      - 127.0.0.1:3002:3002/tcp
