services:
  prometheus:
    image: prom/prometheus:v3.1.0
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./.configs/grafana/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_storage:/prometheus

  grafana: # http://localhost:3000/
    image: grafana/grafana-oss:11.4.0
    restart: unless-stopped
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./.configs/grafana/dashboards:/var/lib/grafana/dashboards
      - ./.configs/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/main.yml
      - ./.configs/grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana_storage:/var/lib/grafana
    depends_on:
      - prometheus

  agent:
    image: grafana/agent:v0.43.4
    restart: unless-stopped
    cap_add:
      - SYS_TIME
    network_mode: host
    volumes:
      - ./.configs/grafana/agent.yml:/etc/agent/agent-config.yml
    entrypoint:
      - /bin/grafana-agent
      - -config.file=/etc/agent/agent-config.yml
    depends_on:
      - prometheus

volumes:
  grafana_storage:
  prometheus_storage:
