{
 "title": "DVR stats",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Upload success rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(dvr_upload_success_count > 0) or vector(0))\r\n  /\r\nsum(dvr_upload_attempt_count > 0) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uploads in progress",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dvr_upload_inprogress_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Upload speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(dvr_upload_byte_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total uploaded bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "dvr_upload_byte_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Upload attempts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dvr_upload_attempt_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload successes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dvr_upload_success_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(dvr_upload_failure_count[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}